services:
    access.user_provider:
        class: AccessBundle\UserProvider
        arguments: [@doctrine_mongodb]

    access.user:
        class: AccessBundle\UserService
        arguments: [@doctrine_mongodb]

    access.api_voter:
        class: AccessBundle\ApiVoter
        public: false
        tags:
            - { name: security.voter }

    access.api_order:
        class: AccessBundle\OrderVoter
        public: false
        tags:
            - { name: security.voter }
