old_sound_rabbit_mq:
  connections:
    default:
      host: 'localhost'
      port: 5672
      user: 'guest'
      password: 'guest'
      vhost: '/'
      lazy: false
      connection_timeout: 3
      read_write_timeout: 3
      keepalive: false
  producers:
    document:
      connection: default
      exchange_options: {name: 'document', type: direct}
  consumers:
    document.invoice:
      connection: default
      exchange_options: {name: 'document', type: direct}
      queue_options: {name: 'document.invoice', routing_keys: [document.invoice]}
      callback: app.document