imports:
    - { resource: "@AppBundle/Resources/config/services.yml" }


services:
    json_rpc.server:
        class: JsonRpcBundle\Server
        calls:
            - [setContainer, ["@service_container"]]
        requirements:
            _switch: "%jsonrpc.switch%"