imports:
    - { resource: listeners.yml }
    - { resource: events.xml }
    - { resource: email_providers.yml }

services:
    app.doctrine_aware:
        class: AppBundle\Service\AbstractDoctrineAware
        arguments: [@doctrine, @logger, @event_dispatcher]
        abstract: true        
    app.warehouse:
        class: AppBundle\Service\WarehouseService
        parent: app.doctrine_aware
        tags:
            - {name: json_rpc.service, method: getAll}        
    app.catalog:
        class: AppBundle\Service\CatalogService
        parent: app.doctrine_aware        
    app.order:
        class: AppBundle\Service\OrderService
        parent: app.doctrine_aware
        tags:
            - {name: json_rpc.service, method: createOrder}            
    order: @app.order    
    warehouse: @app.warehouse    
    app.email:
        class: AppBundle\Service\Communication\EmailService
        public: false
        calls:
            - ["addProvider", [@app.provider_email_external]] 
    app.communication:
        class: AppBundle\Service\Communication\CommunicationService
        arguments: [@app.email, @templating, @translator, @event_dispatcher]
    event_dispatcher:
        class: AppBundle\Event\EventDispatcher
        arguments: [@service_container]        
    app.document:
        class: AppBundle\Service\Document\DocumentService
        arguments: [@templating, @event_dispatcher, @doctrine_mongodb, @old_sound_rabbit_mq.document_producer]
    app.delivery:
        class: AppBundle\Service\DeliveryService
        parent: app.doctrine_aware
    app.authentication:
        class: AppBundle\Service\AuthenticationService
